### ISSUE TITLE
[1.3.0 beta] Text box placeholder label weirdness

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1020]
When a chat is opened via selecting a notification, if Use Chat Name As Placeholder Label is enabled, it behaves oddly. Sometimes it will just say 

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@electronika` in `#android-bugs`.

**Comment by romhacks** [comment]
full text: When a chat is opened via selecting a notification, if Use Chat Name As Placeholder Label is enabled, it behaves oddly. Sometimes it will just say "Bluebubbles" instead of the contact name, and sometimes it will be the phone number instead of the contact name. The issue goes away by exiting the chat and re-entering it

**Comment by romhacks** [comment]
Update: I can no longer reproduce this currently. Might have just been a fluke

**Comment by tneotia** [comment]
This is intended, it is just nullsafety catching null exceptions. It will first check if it can find the contact & if so it will display the contact name, otherwise it will try to display the "address" it got from the mac (so a phone number), and finally it will fallback to just "BlueBubbles".
