### ISSUE TITLE
[Material theme] Multi select bug

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1067]
When in multi select mode via long pressing a chat, the system back key should exit multi select, not close the app.

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@Scarlett` in `#android-bugs`.

**Comment by SoPat712** [comment]
This shouldn't be this hard to fix. Just return WillPopScope instead of material, and have material as the child. In onWillPop, use something along the lines of `parent.widget.selected!.clear();` or `widget.parent.widget.selected = [];` to clear the list of selected chats, and just make sure to return false in onWillPop unless the list `selected`, has at least 1 chat in it.
