### ISSUE TITLE
Dupe messages when disconnect happens as message is sent

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/BlueBubbles-Android-App#1070]
Marking this as high priority because it was not as much of an issue in the pre-flutter2 builds. Now, we are seeing dupes get sent 1, 2, 3, or even 4 times. 

We may need a caching system. I have already switched to hashing the message vars to generate a tempGUID. Probably is worth caching a list of those and checking against it. 

HOWEVER, the issue might be with the flutter socket IO library. It might detect the disconnect and assume the packet wasn't sent, even if it is. So, this might be something I need to fix on the server.

**Comment by CSab6482** [comment]
![Image](https://media.discordapp.net/attachments/768689186801975296/865369449082519552/20210715_190851.jpg)

**Comment by CSab6482** [comment]
This is either the first time or the first time in a long time that I have moved to an older build because of a new bug. I hope this can be fixed soon, but the top priority is Zach's vacation right now 🏖😎
![tempFileForShare_20210716-114942](https://user-images.githubusercontent.com/53708281/126043830-1fc3b39d-1429-4607-a8e2-c63aaea3b312.jpeg)
