### ISSUE TITLE
Compress images on download instead of on load

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1106]
This is likely due to the attachment metadata being loaded into BB. Not sure why it lags the UI since it should all happen in the background. But maybe this is something we need to do via a dart VM so it doesn't lag the UI thread? Not sure

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#android-bugs`.

**Comment by zlshames** [comment]
We may be able to use the Flutter Compute function as documented here: https://docs-flutter-io.firebaseapp.com/flutter/foundation/compute.html

**Comment by tneotia** [comment]
We cannot use compute as our photo manager lib makes calls to `ServiceBinding` and other things that aren't supported while in an isolate.

**Comment by zlshames** [comment]
> We cannot use compute as our photo manager lib makes calls to `ServiceBinding` and other things that aren't supported while in an isolate.

I actually fixed this as the issue was related to my flutter compression code. I disabled it for the share menu. 

Also I am going to change this ticket to make it an enhancement to compress image attachments when they are downloaded, not when they first load into the chat. That is what is causing the lag

**Comment by zlshames** [comment]
We still should call the compress function at the end of the attachment download vs. when the image first loads into the UI, which is probably bad practice

**Comment by tneotia** [comment]
How would we do this because in certain places we want the attachment to be full quality and in others we want it to be compressed? Also we don't ever store the bytes so how would we store the compressed attachment after downloading? We would rather store the full quality image and then compress on demand, right?

**Comment by zlshames** [comment]
> How would we do this because in certain places we want the attachment to be full quality and in others we want it to be compressed? Also we don't ever store the bytes so how would we store the compressed attachment after downloading? We would rather store the full quality image and then compress on demand, right?

We store both. We store the original quality image, then we also store a compressed version, denoted by the following format: `<original filename>.<compression quality>.compressed`, so the compressed file is unique to what the user has the attachment preview quality set at. When the previews load in, the bytes of the compressed image are loaded and cached in the CurrentChat. When you open a chat, the code checks to see if the compressed bytes exist in CurrentChat. If not, see if the compressed file exists. If it does, load the bytes and store it. Otherwise, compress it, then load the compressed bytes. I still want to keep that functionality. I just want to add the call to compress the attachment at the time of attachment download. That way it won't always occur when the user loads up a specific chat. That's what is causing the lag.

**Comment by tneotia** [comment]
I am dumbo, this is pretty easy. Probs like a line of code, lemme write it out real quick and see how it works

**Comment by zlshames** [comment]
> I am dumbo, this is pretty easy. Probs like a line of code, lemme write it out real quick and see how it works

Yep, should just be calling that compress function i linked above in the attachment downloader. We will still want it in the attachment widget, but also have it when it's finished downloading so we kinda pre-cache it to prevent UI lag

**Comment by tneotia** [comment]
Ye just pushed thanks for the info :)
