### ISSUE TITLE
{Request} Let App Always Run in Background permission pop up

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#1159]
as shown here ! [Image] (https://media.discordapp.net/attachments/768689186801975296/868176207034843176/Screenshot_20210723-130136140.jpg)

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@monicow` in `#baffoonery`.

**Comment by zlshames** [comment]
Idk how easy this is to do. I assume it's not easy.

**Comment by tneotia** [comment]
So this is pretty easy but I'm closing this because we shouldn't do this. Apparently apps can get banned from the Play Store by putting the permission line in `AndroidManifest` for this capability. The screenshot is of the Galaxy Watch plugin which is *not* downloaded through Google Play but sideloaded directly onto the device by the Galaxy Wear app.
