### ISSUE TITLE
[Internal Build] Trying to create a new chat with 2 people, send button doesn't work

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#703]
This is happening on my most recent local build, it's not public so shouldn't affect anyone. I just need it tracked so I remember to fix it

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#support`.

**Comment by SoPat712** [comment]
Documenting stuff here. On ios theme, the send button shows up perfectly fine. Something about samsung and material theme makes the text field freak out and it shows the record icon instead of the send icon. On button press, it still creates the new conversation and sends the message, but the first message in a conversation is invisible until a restart

**Comment by SoPat712** [comment]
I can fix the send button icon, I dunno what the invisible first message is about tho

**Comment by zlshames** [comment]
This was fixed. Closing
