### ISSUE TITLE
[Nightly] Connection indicator light sometimes stays infinitely reloading

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Android-App#748]
Even with a solid connection and green dot, sometimes the loading wheel just keeps spinning

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#nightly-bugs`.

**Comment by CSab6482** [comment]
I've only gotten this bug once on the release candidate and it was after a reboot of my phone. I had it happen a bunch on Intellijence's build so I would consider it "fixed"

**Comment by CSab6482** [comment]
I think this is safe to close

**Comment by zlshames** [comment]
Closing, I don't think this is an issue anymore. Also, the indicator is indicating the background syncing. I think it sometimes takes a while due to lots of messages to sync. However, it syncs from newest to oldest, so it _seems_ like everything updated even if it hasn't finished inserting everything into the DB. If this is still an issue, we can re-open it.
