### ISSUE TITLE
If you're in an individual chat, and the person you're chatting with has a contact photo, the "You" avatar on tapback menu has the recipient's contact photo

### ISSUE THREAD

**Issue by CSab6482** [BlueBubblesApp/BlueBubbles-Android-App#908]
I know the title is a mouthful, so feel free to abridge it. This is somewhat related to issue #763, but it's not exactly the same kind of bug. Below is the contact information for an individual, as well as the tapback menu in a conversation that I had with that same person. The avatar displays the recipient's contact photo instead of a blank one or my own (would it be possible to display my own contact photo?)

This is not an issue in group chats.
![Screenshot_20210620-212941_Contacts](https://user-images.githubusercontent.com/53708281/122696196-8bb2e980-d210-11eb-947c-45be0338abb0.jpg)
![Screenshot_20210620-213003](https://user-images.githubusercontent.com/53708281/122696199-8d7cad00-d210-11eb-9013-7bfdbc630d7b.jpg)

**Comment by zlshames** [comment]
I think this fix should be as easy as checking the .isFromMe value of the message for the reaction. Right now we only may be checking if the `message.handle` object is null in order to show "You" as the text. We have to check if the message isFromMe and only display "You" in that case. And if the `message.handle` is null, we need to check the chat.participants list for the other person's handle. 

Now that I'm writing this I think it might be a little more work, so also adding the medium tag as it's easy-medium

**Comment by tneotia** [comment]
Will try to get to this later today if nobody else pushes a PR

**Comment by tneotia** [comment]
Started to mess around with this yesterday a bit and I found it weird that the `Handle` for the reaction contains metadata for the other person even though the reaction is from me. 

We use `.isFromMe` to display "You" but if I understand correctly shouldn't the reaction `Handle` contain my metadata, not the other person's? Nevertheless using `.isFromMe` can fix the contact avatar issue by displaying the "person" icon but I want to try and display the avatar for my contact (if applicable).
